name: Docker Image CI (prod)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive

      - name: Set variables
        id: vars
        run: |
          echo "dt=$(date +'%Y-%m-%dT%H:%M')" >> $GITHUB_OUTPUT
          echo "tag=$(date +'v%Y%m%dT%H%M')" >> $GITHUB_OUTPUT
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:v0.10.6

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ secrets.REGISTRY_NAME }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./Dockerfile.production
          build-args: |
            REACT_APP_DEV_VERSION=${{ steps.vars.outputs.dt }} (commit ${{ steps.vars.outputs.sha_short }})
          cache-from: ${{ secrets.REGISTRY_NAME }}/comdev:latest
          cache-to: type=inline
          push: true
          tags: ${{ secrets.REGISTRY_NAME }}/comdev:${{ steps.vars.outputs.tag }}

      - name: Output version
        run: |
          echo "Release tag: [${{ steps.vars.outputs.tag }}]"
